// 250 original math problem puzzles — 4 difficulty levels
export interface MathItem { key: string; text: string; answer: number; diff: 1|2|3|4; }

export const MP_ALL: MathItem[] = [
  // ── DIFF 1 (65 items) ──────────────────────────────────────────────────
  { key:'MP001', text:'2 + 3 × 4 = ?',                                              answer:14,   diff:1 },
  { key:'MP002', text:'(5 + 3) × 2 = ?',                                            answer:16,   diff:1 },
  { key:'MP003', text:'20 − 3 × 4 = ?',                                             answer:8,    diff:1 },
  { key:'MP004', text:'48 ÷ 6 + 3 = ?',                                             answer:11,   diff:1 },
  { key:'MP005', text:'7 × 8 − 10 = ?',                                             answer:46,   diff:1 },
  { key:'MP006', text:'12 × 12 = ?',                                                answer:144,  diff:1 },
  { key:'MP007', text:'144 ÷ 12 = ?',                                               answer:12,   diff:1 },
  { key:'MP008', text:'15² = ?',                                                    answer:225,  diff:1 },
  { key:'MP009', text:'√64 = ?',                                                    answer:8,    diff:1 },
  { key:'MP010', text:'√169 = ?',                                                   answer:13,   diff:1 },
  { key:'MP011', text:'Сколько минут в 3 часах?',                                   answer:180,  diff:1 },
  { key:'MP012', text:'Сколько секунд в 5 минутах?',                                answer:300,  diff:1 },
  { key:'MP013', text:'Сколько часов в неделе?',                                    answer:168,  diff:1 },
  { key:'MP014', text:'Сколько дней в 4 неделях?',                                  answer:28,   diff:1 },
  { key:'MP015', text:'3 + 5 + 7 + 9 + 11 = ?',                                    answer:35,   diff:1 },
  { key:'MP016', text:'2 + 4 + 6 + 8 + 10 = ?',                                    answer:30,   diff:1 },
  { key:'MP017', text:'1 + 2 + 3 + ... + 9 = ?',                                   answer:45,   diff:1 },
  { key:'MP018', text:'Периметр квадрата со стороной 8 = ?',                        answer:32,   diff:1 },
  { key:'MP019', text:'Площадь прямоугольника 6 × 9 = ?',                           answer:54,   diff:1 },
  { key:'MP020', text:'Площадь квадрата со стороной 7 = ?',                         answer:49,   diff:1 },
  { key:'MP021', text:'2³ + 3² = ?',                                                answer:17,   diff:1 },
  { key:'MP022', text:'4² − 3² = ?',                                                answer:7,    diff:1 },
  { key:'MP023', text:'5² + 5 = ?',                                                 answer:30,   diff:1 },
  { key:'MP024', text:'Найдите x: x + 7 = 15',                                      answer:8,    diff:1 },
  { key:'MP025', text:'Найдите x: x − 4 = 11',                                      answer:15,   diff:1 },
  { key:'MP026', text:'Найдите x: 3x = 21',                                         answer:7,    diff:1 },
  { key:'MP027', text:'Найдите x: x/4 = 9',                                         answer:36,   diff:1 },
  { key:'MP028', text:'Если x = 5, чему равно 4x − 3?',                             answer:17,   diff:1 },
  { key:'MP029', text:'Если y = 3, чему равно 2y² + 1?',                            answer:19,   diff:1 },
  { key:'MP030', text:'10% от 250 = ?',                                             answer:25,   diff:1 },
  { key:'MP031', text:'20% от 150 = ?',                                             answer:30,   diff:1 },
  { key:'MP032', text:'50% от 84 = ?',                                              answer:42,   diff:1 },
  { key:'MP033', text:'75% от 80 = ?',                                              answer:60,   diff:1 },
  { key:'MP034', text:'5% от 200 = ?',                                              answer:10,   diff:1 },
  { key:'MP035', text:'Число 48 — сколько процентов от 120?',                       answer:40,   diff:1 },
  { key:'MP036', text:'Число 36 — сколько процентов от 180?',                       answer:20,   diff:1 },
  { key:'MP037', text:'В корзине 12 яблок и 8 груш. Сколько всего фруктов?',        answer:20,   diff:1 },
  { key:'MP038', text:'Купили 5 кг по 40 руб/кг. Сколько заплатили?',               answer:200,  diff:1 },
  { key:'MP039', text:'Из 100 вычли 37, добавили 15. Итог = ?',                     answer:78,   diff:1 },
  { key:'MP040', text:'7 × 6 + 8 × 3 = ?',                                         answer:66,   diff:1 },
  { key:'MP041', text:'Следующее нечётное число после 29 = ?',                       answer:31,   diff:1 },
  { key:'MP042', text:'Наибольший общий делитель 24 и 36 = ?',                      answer:12,   diff:1 },
  { key:'MP043', text:'Наименьшее общее кратное 4 и 6 = ?',                         answer:12,   diff:1 },
  { key:'MP044', text:'НОК(3, 5) = ?',                                              answer:15,   diff:1 },
  { key:'MP045', text:'НОД(18, 24) = ?',                                            answer:6,    diff:1 },
  { key:'MP046', text:'123 + 456 + 789 = ?',                                        answer:1368, diff:1 },
  { key:'MP047', text:'1000 − 373 = ?',                                             answer:627,  diff:1 },
  { key:'MP048', text:'25 × 4 × 3 = ?',                                             answer:300,  diff:1 },
  { key:'MP049', text:'Если поезд едет 90 км/ч, за 2 часа пройдёт = ? км',         answer:180,  diff:1 },
  { key:'MP050', text:'Если велосипед едет 15 км/ч, за 3 ч пройдёт = ? км',        answer:45,   diff:1 },
  { key:'MP051', text:'Сколько чётных чисел от 1 до 20?',                           answer:10,   diff:1 },
  { key:'MP052', text:'Сколько простых чисел от 1 до 10?',                          answer:4,    diff:1 },
  { key:'MP053', text:'2⁰ + 2¹ + 2² + 2³ = ?',                                     answer:15,   diff:1 },
  { key:'MP054', text:'3! (три факториал) = ?',                                     answer:6,    diff:1 },
  { key:'MP055', text:'4! = ?',                                                     answer:24,   diff:1 },
  { key:'MP056', text:'Сумма углов треугольника = ?°',                              answer:180,  diff:1 },
  { key:'MP057', text:'Сумма углов прямоугольника = ?°',                            answer:360,  diff:1 },
  { key:'MP058', text:'Угол прямоугольного треугольника рядом с 90° = ?° если другой 35°', answer:55, diff:1 },
  { key:'MP059', text:'У квадрата n осей симметрии. n = ?',                         answer:4,    diff:1 },
  { key:'MP060', text:'Сумма первых 5 простых чисел = ?',                           answer:28,   diff:1 },
  { key:'MP061', text:'9 × 9 − 1 = ?',                                              answer:80,   diff:1 },
  { key:'MP062', text:'(10 + 10) × (10 − 10) = ?',                                 answer:0,    diff:1 },
  { key:'MP063', text:'Среднее 10, 20, 30 = ?',                                     answer:20,   diff:1 },
  { key:'MP064', text:'Среднее 5, 10, 15, 20 = ?',                                  answer:13,   diff:1 },
  { key:'MP065', text:'Сколько цифр в числе 1 000 000?',                            answer:7,    diff:1 },

  // ── DIFF 2 (70 items) ──────────────────────────────────────────────────
  { key:'MP066', text:'Найдите x: 2x + 5 = 17',                                     answer:6,    diff:2 },
  { key:'MP067', text:'Найдите x: 3x − 8 = 13',                                     answer:7,    diff:2 },
  { key:'MP068', text:'Найдите x: 5x + 2 = 3x + 12',                               answer:5,    diff:2 },
  { key:'MP069', text:'Найдите x: 4x − 3 = 2x + 7',                                answer:5,    diff:2 },
  { key:'MP070', text:'Найдите x: x/3 + 4 = 9',                                     answer:15,   diff:2 },
  { key:'MP071', text:'Найдите x: 2(x + 3) = 14',                                   answer:4,    diff:2 },
  { key:'MP072', text:'Найдите x: 3(2x − 1) = 21',                                  answer:4,    diff:2 },
  { key:'MP073', text:'Найдите x: (x + 4)/2 = 7',                                   answer:10,   diff:2 },
  { key:'MP074', text:'30% от числа равно 24. Само число = ?',                       answer:80,   diff:2 },
  { key:'MP075', text:'40% от числа равно 56. Само число = ?',                       answer:140,  diff:2 },
  { key:'MP076', text:'Число увеличили на 25%. Стало 75. Было = ?',                  answer:60,   diff:2 },
  { key:'MP077', text:'Число уменьшили на 20%. Стало 64. Было = ?',                  answer:80,   diff:2 },
  { key:'MP078', text:'Цена выросла на 15% до 115 руб. Была = ? руб',               answer:100,  diff:2 },
  { key:'MP079', text:'16 × 25 = ?',                                                answer:400,  diff:2 },
  { key:'MP080', text:'18 × 15 = ?',                                                answer:270,  diff:2 },
  { key:'MP081', text:'24 × 13 = ?',                                                answer:312,  diff:2 },
  { key:'MP082', text:'37 × 8 = ?',                                                 answer:296,  diff:2 },
  { key:'MP083', text:'11² = ?',                                                    answer:121,  diff:2 },
  { key:'MP084', text:'13² = ?',                                                    answer:169,  diff:2 },
  { key:'MP085', text:'14² = ?',                                                    answer:196,  diff:2 },
  { key:'MP086', text:'√225 = ?',                                                   answer:15,   diff:2 },
  { key:'MP087', text:'√289 = ?',                                                   answer:17,   diff:2 },
  { key:'MP088', text:'2⁸ = ?',                                                     answer:256,  diff:2 },
  { key:'MP089', text:'3⁵ = ?',                                                     answer:243,  diff:2 },
  { key:'MP090', text:'2¹⁰ = ?',                                                    answer:1024, diff:2 },
  { key:'MP091', text:'Сумма от 1 до 15 = ?',                                       answer:120,  diff:2 },
  { key:'MP092', text:'Сумма от 1 до 20 = ?',                                       answer:210,  diff:2 },
  { key:'MP093', text:'Сумма от 1 до 100 = ?',                                      answer:5050, diff:2 },
  { key:'MP094', text:'5! = ?',                                                     answer:120,  diff:2 },
  { key:'MP095', text:'6! = ?',                                                     answer:720,  diff:2 },
  { key:'MP096', text:'Площадь треугольника с основанием 12 и высотой 7 = ?',        answer:42,   diff:2 },
  { key:'MP097', text:'Площадь трапеции с основаниями 6, 10 и высотой 4 = ?',       answer:32,   diff:2 },
  { key:'MP098', text:'Площадь круга с радиусом 7 (π≈3) = ?',                       answer:147,  diff:2 },
  { key:'MP099', text:'Длина окружности с радиусом 5 (π≈3) = ?',                    answer:30,   diff:2 },
  { key:'MP100', text:'Объём куба со стороной 4 = ?',                               answer:64,   diff:2 },
  { key:'MP101', text:'Объём прямоуг. параллелепипеда 3×4×5 = ?',                   answer:60,   diff:2 },
  { key:'MP102', text:'Сумма углов шестиугольника = ?°',                            answer:720,  diff:2 },
  { key:'MP103', text:'Сумма углов восьмиугольника = ?°',                           answer:1080, diff:2 },
  { key:'MP104', text:'3 рабочих строят дом за 9 дней. 9 рабочих построят за = ? дней', answer:3, diff:2 },
  { key:'MP105', text:'Велосипедист за 4 ч проехал 60 км. Скорость = ? км/ч',       answer:15,   diff:2 },
  { key:'MP106', text:'Два поезда выехали навстречу за 5 ч: 80 и 120 км/ч. Расстояние = ? км', answer:1000, diff:2 },
  { key:'MP107', text:'Из 200 задач решено 160. Процент решённых = ?%',             answer:80,   diff:2 },
  { key:'MP108', text:'Студент правильно ответил на 18 из 24. Точность = ?%',        answer:75,   diff:2 },
  { key:'MP109', text:'Прибыль 360 руб — 40% от продаж. Продажи = ? руб',           answer:900,  diff:2 },
  { key:'MP110', text:'C(5,2) — выбрать 2 из 5 = ?',                               answer:10,   diff:2 },
  { key:'MP111', text:'C(6,2) = ?',                                                 answer:15,   diff:2 },
  { key:'MP112', text:'C(7,3) = ?',                                                 answer:35,   diff:2 },
  { key:'MP113', text:'Сколько способов расставить 4 книги в ряд? (4!) = ?',        answer:24,   diff:2 },
  { key:'MP114', text:'P(5) = 5! = ?',                                              answer:120,  diff:2 },
  { key:'MP115', text:'Найдите y: 2y + 3 = y + 10',                                answer:7,    diff:2 },
  { key:'MP116', text:'Найдите a: a² = 49',                                         answer:7,    diff:2 },
  { key:'MP117', text:'Найдите a: a² + 16 = 25',                                    answer:3,    diff:2 },
  { key:'MP118', text:'Среднее 12, 18, 24, 30, 36 = ?',                             answer:24,   diff:2 },
  { key:'MP119', text:'Медиана чисел 3, 1, 4, 1, 5, 9, 2, 6 = ?',                 answer:4,    diff:2 },
  { key:'MP120', text:'Скидка 30% с 200 руб = ? руб',                               answer:140,  diff:2 },
  { key:'MP121', text:'НДС 20% к цене 500 руб = итого ? руб',                       answer:600,  diff:2 },
  { key:'MP122', text:'Число 80 составляет 64% от чего? ответ = ?',                 answer:125,  diff:2 },
  { key:'MP123', text:'В классе 28 учеников. 25% отличники. Сколько отличников?',   answer:7,    diff:2 },
  { key:'MP124', text:'Товар стоил 400, стал 500. Рост в процентах = ?%',           answer:25,   diff:2 },
  { key:'MP125', text:'Число уменьшили на 15%. Стало 85. Было = ?',                 answer:100,  diff:2 },
  { key:'MP126', text:'(a+b)² если a=3, b=4 = ?',                                  answer:49,   diff:2 },
  { key:'MP127', text:'a² + 2ab + b² если a=2, b=5 = ?',                           answer:49,   diff:2 },
  { key:'MP128', text:'Чему равен корень из 2 в квадрате плюс 2 в квадрате? (√8 ≈)',answer:3,   diff:2 },
  { key:'MP129', text:'Периметр правильного шестиугольника со стороной 5 = ?',      answer:30,   diff:2 },
  { key:'MP130', text:'Диагональ квадрата 10√2. Сторона = ?',                       answer:10,   diff:2 },
  { key:'MP131', text:'Если a×b = 72 и a+b = 17, то (a-b)² = ?',                  answer:1,    diff:2 },
  { key:'MP132', text:'Сколько простых чисел от 1 до 30?',                          answer:10,   diff:2 },
  { key:'MP133', text:'Через 6 лет Коле будет 25. Сейчас Коле = ? лет',             answer:19,   diff:2 },
  { key:'MP134', text:'Маша вдвое старше Пети. Вместе им 30. Маше = ? лет',         answer:20,   diff:2 },
  { key:'MP135', text:'Числовое значение XLVII в римских = ?',                      answer:47,   diff:2 },

  // ── DIFF 3 (65 items) ──────────────────────────────────────────────────
  { key:'MP136', text:'Найдите x: x² − 5x + 6 = 0, большее решение',               answer:3,    diff:3 },
  { key:'MP137', text:'Найдите x: x² − 7x + 12 = 0, меньшее решение',              answer:3,    diff:3 },
  { key:'MP138', text:'Найдите x: x² − 9 = 0, положительное решение',              answer:3,    diff:3 },
  { key:'MP139', text:'Найдите x: 2x² − 8 = 0, положительное x',                   answer:2,    diff:3 },
  { key:'MP140', text:'log₂(64) = ?',                                               answer:6,    diff:3 },
  { key:'MP141', text:'log₃(81) = ?',                                               answer:4,    diff:3 },
  { key:'MP142', text:'log₁₀(10000) = ?',                                           answer:4,    diff:3 },
  { key:'MP143', text:'2^x = 128 → x = ?',                                          answer:7,    diff:3 },
  { key:'MP144', text:'3^x = 729 → x = ?',                                          answer:6,    diff:3 },
  { key:'MP145', text:'Сумма первых n членов арифм. прогрессии: a₁=3, d=4, n=10 = ?', answer:210, diff:3 },
  { key:'MP146', text:'n-й член арифм. прогр. a₁=2, d=5, n=8 = ?',                answer:37,   diff:3 },
  { key:'MP147', text:'Сумма геом. прогрессии: b₁=2, q=3, n=4 = ?',               answer:80,   diff:3 },
  { key:'MP148', text:'Геом. прогрессия: b₁=4, q=2, b₅ = ?',                      answer:64,   diff:3 },
  { key:'MP149', text:'Гипотенуза прямоугольного треугольника с катетами 8 и 15 = ?', answer:17, diff:3 },
  { key:'MP150', text:'Катет прямоуг. треугольника, если гипотенуза 13, другой катет 5 = ?', answer:12, diff:3 },
  { key:'MP151', text:'Площадь правильного треугольника со стороной 6 (≈ целое)=?', answer:16,  diff:3 },
  { key:'MP152', text:'Объём шара с радиусом 3 (V=4πr³/3, π≈3) = ?',              answer:108,  diff:3 },
  { key:'MP153', text:'Поверхность куба со стороной 5 = ?',                         answer:150,  diff:3 },
  { key:'MP154', text:'Диагональ куба со стороной 2 (≈ целое, √12 ≈ 3) = ?',       answer:3,    diff:3 },
  { key:'MP155', text:'C(10, 3) = ?',                                               answer:120,  diff:3 },
  { key:'MP156', text:'C(8, 4) = ?',                                                answer:70,   diff:3 },
  { key:'MP157', text:'C(12, 2) = ?',                                               answer:66,   diff:3 },
  { key:'MP158', text:'A(5, 3) = размещения = ?',                                   answer:60,   diff:3 },
  { key:'MP159', text:'A(6, 2) = ?',                                                answer:30,   diff:3 },
  { key:'MP160', text:'Если 6 команд, каждая с каждой 1 матч. Всего матчей = ?',   answer:15,   diff:3 },
  { key:'MP161', text:'Сколько диагоналей у восьмиугольника?',                      answer:20,   diff:3 },
  { key:'MP162', text:'Сколько диагоналей у десятиугольника?',                      answer:35,   diff:3 },
  { key:'MP163', text:'Машина проехала 300 км: 2ч 60км/ч и 3ч х км/ч. Средняя скорость = ?', answer:60, diff:3 },
  { key:'MP164', text:'Бассейн наполняется за 3ч, опустошается за 6ч. Полный → опустеет за?', answer:6, diff:3 },
  { key:'MP165', text:'Два крана: 4ч и 6ч. Вместе наполнят бассейн за = ? ч',      answer:2,    diff:3 },
  { key:'MP166', text:'Треугольник: стороны 7, 24, 25. Площадь = ?',               answer:84,   diff:3 },
  { key:'MP167', text:'Сторона ромба 10, острый угол 30°. Площадь = ? (sin30=0.5)', answer:50,  diff:3 },
  { key:'MP168', text:'Вписанная в квадрат 8×8 окружность. Площадь круга (π≈3) = ?', answer:48, diff:3 },
  { key:'MP169', text:'Правильная пирамида: квадратное основание 6, высота 4. Объём = ?', answer:48, diff:3 },
  { key:'MP170', text:'Конус: радиус 3, высота 4. Объём (V=πr²h/3, π≈3) = ?',     answer:36,   diff:3 },
  { key:'MP171', text:'Число 45 увеличить на 40%, затем уменьшить на 30%. Итог = ?', answer:63, diff:3 },
  { key:'MP172', text:'Цена выросла на 20%, затем ещё на 25%. Итого рост = ?%',     answer:50,   diff:3 },
  { key:'MP173', text:'Цена снизилась на 10%, затем на 10%. Итого снижение = ?%',   answer:19,   diff:3 },
  { key:'MP174', text:'Система: x+y=10, x−y=4. Найдите x',                         answer:7,    diff:3 },
  { key:'MP175', text:'Система: 2x+y=11, x+2y=10. Найдите x',                      answer:4,    diff:3 },
  { key:'MP176', text:'Система: 3x−y=7, x+y=5. Найдите y',                         answer:2,    diff:3 },
  { key:'MP177', text:'Число x: x/5 + x/3 = 16 → x = ?',                           answer:30,   diff:3 },
  { key:'MP178', text:'Дробь 3/4 + 1/6 = ? (в шестых)',                             answer:11,   diff:3 },
  { key:'MP179', text:'3/4 × 8/9 = ? (числитель × знаменатель = числитель ответа, если знам=3)', answer:2, diff:3 },
  { key:'MP180', text:'7! / 5! = ?',                                                answer:42,   diff:3 },
  { key:'MP181', text:'8! / 6! = ?',                                                answer:56,   diff:3 },
  { key:'MP182', text:'10! / 8! = ?',                                               answer:90,   diff:3 },
  { key:'MP183', text:'Найдите k: k(k+1) = 56',                                     answer:7,    diff:3 },
  { key:'MP184', text:'Найдите n: n² + n = 72',                                     answer:8,    diff:3 },
  { key:'MP185', text:'Сколько двузначных чисел делится на 7?',                     answer:13,   diff:3 },
  { key:'MP186', text:'Сколько трёхзначных чисел делится на 11?',                   answer:82,   diff:3 },
  { key:'MP187', text:'Наименьшее трёхзначное кратное 13 = ?',                      answer:104,  diff:3 },
  { key:'MP188', text:'Сумма всех делителей числа 28 (кроме самого) = ?',           answer:28,   diff:3 },
  { key:'MP189', text:'Квадрат суммы: (a+b)²=81, ab=14. a²+b² = ?',               answer:53,   diff:3 },
  { key:'MP190', text:'(a-b)²=25, ab=6. a²+b² = ?',                                answer:37,   diff:3 },
  { key:'MP191', text:'Скорость 90 км/ч → м/с = ?',                                answer:25,   diff:3 },
  { key:'MP192', text:'Скорость 72 км/ч → м/с = ?',                                answer:20,   diff:3 },
  { key:'MP193', text:'Поезд 400 м идёт мимо столба за 20 с. Скорость = ? м/с',    answer:20,   diff:3 },
  { key:'MP194', text:'Поезд 600 м проходит мост 400 м за 25 с. Скорость = ? м/с', answer:40,   diff:3 },
  { key:'MP195', text:'Работник за 10 дней, другой за 15. Вместе = ? дней',         answer:6,    diff:3 },
  { key:'MP196', text:'Три рабочих: 6, 12 и 4 дня. Вместе = ? дней',               answer:2,    diff:3 },
  { key:'MP197', text:'Чему равна x в прогрессии 3, x, 27 (геометрич.)? x = ?',    answer:9,    diff:3 },
  { key:'MP198', text:'Среднее геометрическое 4 и 36 = ?',                          answer:12,   diff:3 },
  { key:'MP199', text:'Гармоническое среднее 4 и 6 = ?',                            answer:5,    diff:3 },
  { key:'MP200', text:'Угол в правильном шестиугольнике = ?°',                      answer:120,  diff:3 },

  // ── DIFF 4 (50 items) ──────────────────────────────────────────────────
  { key:'MP201', text:'log₂(log₂(256)) = ?',                                        answer:3,    diff:4 },
  { key:'MP202', text:'log₃(log₃(729)) = ?',                                        answer:2,    diff:4 },
  { key:'MP203', text:'Найдите x: 4^x = 8^(x-1) → x = ?',                          answer:3,    diff:4 },
  { key:'MP204', text:'Сумма бесконечной геом. прогрессии: b₁=6, q=1/2 = ?',       answer:12,   diff:4 },
  { key:'MP205', text:'Сумма: b₁=9, q=1/3 = ?',                                    answer:14,   diff:4 },
  { key:'MP206', text:'C(15,2) = ?',                                                answer:105,  diff:4 },
  { key:'MP207', text:'C(20,3) = ?',                                                answer:1140, diff:4 },
  { key:'MP208', text:'Вероятность: из 52 карт 3 туза подряд без возврата. Числитель C(4,3)=4, C(52,3)=22100. 4/22100 = упростить до 1/?', answer:5525, diff:4 },
  { key:'MP209', text:'Число сочетаний с повторениями C(5+3-1, 3) = C(7,3) = ?',   answer:35,   diff:4 },
  { key:'MP210', text:'Сколько анаграмм слова «КОРЕНЬ» (6 букв, без повторений) = ?', answer:720, diff:4 },
  { key:'MP211', text:'Сколько анаграмм «МАМА» (4 буквы, 2 повторения) = ?',       answer:12,   diff:4 },
  { key:'MP212', text:'Сколько 4-значных чисел из цифр 1,2,3,4 без повторений = ?', answer:24,  diff:4 },
  { key:'MP213', text:'Цифры 0,1,2,3,4. 4-значные числа без нуля вначале = ?',      answer:96,   diff:4 },
  { key:'MP214', text:'Диагонали выпуклого 10-угольника: n(n-3)/2 = ?',             answer:35,   diff:4 },
  { key:'MP215', text:'Сколько рукопожатий при 12 людях?',                          answer:66,   diff:4 },
  { key:'MP216', text:'12 команд, двойной круговой. Всего матчей = ?',              answer:132,  diff:4 },
  { key:'MP217', text:'Интеграл ∫0¹ x dx = ? (площадь треугольника 0.5×1×1)',       answer:1,    diff:4 },
  { key:'MP218', text:'Производная f(x)=3x²+2x+1 в точке x=2 = ?',                 answer:14,   diff:4 },
  { key:'MP219', text:'Производная f(x)=x³ в точке x=3 = ?',                       answer:27,   diff:4 },
  { key:'MP220', text:'Если f(x)=x²-4x+4, f(3) = ?',                               answer:1,    diff:4 },
  { key:'MP221', text:'Корни уравнения x²-5x+6=0. Их произведение = ?',             answer:6,    diff:4 },
  { key:'MP222', text:'Дискриминант x²-6x+5=0: D = b²-4ac = ?',                   answer:16,   diff:4 },
  { key:'MP223', text:'Сумма корней уравнения 2x²-10x+8=0 = ?',                    answer:5,    diff:4 },
  { key:'MP224', text:'Произведение корней 3x²-12x+9=0 = ?',                       answer:3,    diff:4 },
  { key:'MP225', text:'Золотое сечение φ=(1+√5)/2 ≈ ? (умножьте на 100 и округлите)', answer:162, diff:4 },
  { key:'MP226', text:'Формула Эйлера: e^(iπ)+1 = ?',                              answer:0,    diff:4 },
  { key:'MP227', text:'sin(30°) × 10 = ?',                                         answer:5,    diff:4 },
  { key:'MP228', text:'cos(60°) × 20 = ?',                                         answer:10,   diff:4 },
  { key:'MP229', text:'tan(45°) × 7 = ?',                                          answer:7,    diff:4 },
  { key:'MP230', text:'Остаток от деления 2¹⁰⁰ на 3 = ?',                          answer:1,    diff:4 },
  { key:'MP231', text:'Остаток от деления 7¹⁰⁰ на 5 = ?',                          answer:1,    diff:4 },
  { key:'MP232', text:'Последняя цифра числа 7⁴⁰ = ?',                             answer:1,    diff:4 },
  { key:'MP233', text:'Последняя цифра числа 3¹⁰⁰ = ?',                            answer:1,    diff:4 },
  { key:'MP234', text:'Наибольший общий делитель 2024 и 2025 = ?',                  answer:1,    diff:4 },
  { key:'MP235', text:'Сколько нулей в конце числа 100! = ?',                       answer:24,   diff:4 },
  { key:'MP236', text:'Сколько нулей в конце 50! = ?',                              answer:12,   diff:4 },
  { key:'MP237', text:'Мощность множества всех подмножеств {1,2,3,4,5} = 2^5 = ?', answer:32,   diff:4 },
  { key:'MP238', text:'Модулярное уравнение: x ≡ 3 (mod 7), x ≡ 2 (mod 5). Наим. положит. x = ?', answer:17, diff:4 },
  { key:'MP239', text:'Число Эйлера φ(12) = ?',                                     answer:4,    diff:4 },
  { key:'MP240', text:'φ(30) = ?',                                                  answer:8,    diff:4 },
  { key:'MP241', text:'φ(100) = ?',                                                 answer:40,   diff:4 },
  { key:'MP242', text:'В n-мерном пространстве гиперкуб имеет 2^n вершин. n=6: вершин = ?', answer:64, diff:4 },
  { key:'MP243', text:'Рекуррентность T(n)=2T(n/2)+n. T(8) если T(1)=1 = ?',       answer:24,   diff:4 },
  { key:'MP244', text:'Число Рамсея R(3,3)=?',                                     answer:6,    diff:4 },
  { key:'MP245', text:'Прогрессия: 1/(1×2)+1/(2×3)+...+1/(9×10) = ?/10',           answer:9,    diff:4 },
  { key:'MP246', text:'Биномиальный коэффициент C(10,5) = ?',                       answer:252,  diff:4 },
  { key:'MP247', text:'Сумма C(6,0)+C(6,1)+C(6,2)+...+C(6,6) = ?',                answer:64,   diff:4 },
  { key:'MP248', text:'Число Белла B₄ = ?',                                         answer:15,   diff:4 },
  { key:'MP249', text:'Минимальное количество ходов для Ханойских башень из 6 дисков = 2^6-1 = ?', answer:63, diff:4 },
  { key:'MP250', text:'Если P(A)=0.3, P(B)=0.4, A и B независимы. P(A∪B) = ?% (умножить на 100)', answer:58, diff:4 },
];
